New version: improved and expanded

diff --git a/server/archlinux-setup b/server/archlinux-setup
--- a/server/archlinux-setup
+++ b/server/archlinux-setup
@@ -1,261 +1,211 @@
 #!/bin/sh -e
 
-RED="\033[0;31m"
-GREEN="\033[0;32m"
-BLUE="\033[0;34m"
-YELLOW="\033[0;33m"
-RC="\033[0m"
+MIRROR="Brazil" 
+TIMEZONE="America/Sao_Paulo"
+KEYMAP="br-abnt2"
 
-initScript() {
+checkEnv() {
     if [ ! -f /run/archiso/bootmnt/arch/x86_64/airootfs.sfs ]; then
-        printf "%b\n" "${RED}ERROR: Archiso was not detected${RC}"
+        printf "%b\n" "ERROR: Archiso was not detected"
         exit 1
     fi
 
-    if [ ! -d /sys/firmware/efi ]; then
-        printf "%b\n" "${RED}ERROR: Only UEFI 64-bit systems are supported${RC}"
+    if [ -d /sys/firmware/efi ]; then
+        if [ "$(cat /sys/firmware/efi/fw_platform_size)" != "64" ]; then
+            printf "%b\n" "ERROR: Only 64-bit UEFI systems are supported"
+            exit 1
+        fi
+    else
+        printf "%b\n" "ERROR: Only 64-bit UEFI systems are supported"
         exit 1
     fi
 
     if [ "$(id -u)" -ne 0 ]; then
-        printf "%b\n" "${RED}ERROR: Root privileges needed${RC}"
+        printf "%b\n" "ERROR: Root privileges needed"
         exit 1
     fi
 
     if [ -f /var/lib/pacman/db.lck ]; then
         if pgrep -x pacman >/dev/null 2>&1; then
-            printf "%b\n" "${RED}ERROR: Pacman must be closed${RC}"
+            printf "%b\n" "ERROR: Pacman must be closed"
             exit 1
         else
             rm -f /var/lib/pacman/db.lck
         fi
     fi
-
-    printf "%b\n" "${GREEN}Getting pacman ready...${RC}"    
-    pacman-key --init >/dev/null 2>&1
-    pacman-key --populate archlinux >/dev/null 2>&1
-    pacman -Sy --noconfirm --needed archlinux-keyring >/dev/null 2>&1 || {
-        printf "%b\n" "${RED}ERROR: Keyring update failed${RC}" >&2
-        exit 1
-    }
-
-    if ! command -v fzf >/dev/null 2>&1; then
-        printf "%b\n" "${GREEN}Installing fuzzy finder...${RC}"
-        pacman -S --noconfirm --needed fzf >/dev/null 2>&1 || {
-            printf "%b\n" "${RED}ERROR: Fzf install failed${RC}" >&2
-            exit 1
-        }
-    fi
-
-    clear
-    setfont ter-v18b
 }
 
-userInfo() {
+userInformation() {
     while :; do
-        printf "\n%b " "${BLUE}Enter your username:${RC}"
+        printf "\n%b " "Enter your username:"
         read -r username
-        username=$(printf "%s" "${username}" | xargs | tr "[:upper:]" "[:lower:]")
-        if [ "${username}" != "root" ] && printf "%s" "${username}" | grep -Eq "^[a-z][-a-z0-9_]*\$"; then
-            USER="${username}"
+        username=$(printf "%s" "$username" | xargs | tr "[:upper:]" "[:lower:]")
+        if [ "$username" != "root" ] && printf "%s" "$username" | grep -Eq "^[a-z][-a-z0-9_]*\$"; then
+            USER="$username"
             break
         else
-            printf "%b\n" "${YELLOW}WARNING:${RC} Invalid username"
+            printf "%b\n" "WARNING: Invalid username"
         fi
     done
 
     while :; do
-        printf "\n%b " "${BLUE}Enter your password:${RC}"
+        printf "\n%b " "Enter your password:"
         stty -echo
         read -r password
         stty echo
 
-        printf "\n%b " "${BLUE}Verify your password:${RC}"
+        printf "\n%b " "Verify your password:"
         stty -echo
         read -r verify
         stty echo
 
-        if [ "${password}" != "${verify}" ]; then
-            printf "\n%b\n" "${YELLOW}WARNING:${RC} Passwords do not match"
-        elif [ "${password}" = "${verify}" ] && [ -n "${password}" ]; then
-            PASSWD="${password}"
+        if [ "$password" != "$verify" ]; then
+            printf "\n%b\n" "WARNING: Passwords do not match"
+        elif [ "$password" = "$verify" ] && [ -n "$password" ]; then
+            PASSWORD="$password"
             break
         else
-            printf "\n%b\n" "${YELLOW}WARNING:${RC} Invalid password"
+            printf "\n%b\n" "WARNING: Invalid password"
         fi  
     done
 
     while :; do
-        printf "\n\n%b " "${BLUE}Name your machine:${RC}"
+        printf "\n\n%b " "Name your machine:"
         read -r hostname
-        hostname=$(printf "%s" "${hostname}" | xargs | tr "[:upper:]" "[:lower:]")
-        if printf "%s" "${hostname}" | grep -Eq "^(([a-zA-Z0-9]|[a-zA-Z0-9][a-zA-Z0-9\-]{0,61}[a-zA-Z0-9])\.)*([a-zA-Z0-9]|[a-zA-Z0-9][a-zA-Z0-9\-]{0,61}[a-zA-Z0-9])$"; then
-            HOST="${hostname}"
+        hostname=$(printf "%s" "$hostname" | xargs | tr "[:upper:]" "[:lower:]")
+        if printf "%s" "$hostname" | grep -Eq "^(([a-zA-Z0-9]|[a-zA-Z0-9][a-zA-Z0-9\-]{0,61}[a-zA-Z0-9])\.)*([a-zA-Z0-9]|[a-zA-Z0-9][a-zA-Z0-9\-]{0,61}[a-zA-Z0-9])$"; then
+            HOSTNAME="$hostname"
             break
         else
-            printf "%b" "${YELLOW}WARNING:${RC} Invalid hostname"
+            printf "%b" "WARNING: Invalid hostname"
         fi
     done
 }
 
-fuzzySelection() {
-    printf "%b\n" "${options}" | fzf --prompt "${prompt}"
-}
-
 diskSelection() {
-    options=$(lsblk -dn -o NAME,SIZE,TYPE,TRAN | awk '$3 == "disk" && $4 != "usb" && $1 !~ /^(loop|ram|sr|fd)/ {printf "/dev/%s (%s)\n", $1, $2}')
-    prompt="Select a disk: "
-    selected=$(fuzzySelection)
-    DISK=$(printf "%s" "${selected}" | tr -s ' ' | cut -d' ' -f1)
+    while :; do
+        printf "%b\n" "Available disks:"
+        lsblk -dn -o NAME,SIZE,TYPE,TRAN | awk '$3 == "disk" && $4 != "usb" && $1 !~ /^(loop|ram|sr|fd)/ {printf "%s (%s)\n", $1, $2}'
+
+        read -rp "Enter the desired disk (e.g. nvme0n1): " INPUT_DISK
+        DISK="/dev/$INPUT_DISK"
+
+        if [ ! -b "$DISK" ]; then
+            printf "%b\n" "WARNING: Invalid device"
+        else
+            break
+        fi
+    done
 }
 
-regionSelection() {
-    options=$(curl -fs http://bin.christitus.com/raw/dalopenori)
-    prompt="Select a mirror: "
-    COUNTRY=$(fuzzySelection)
+diskFormat() {
+    umount -A --recursive /mnt || true
+    sgdisk -Z "$DISK"
+    sgdisk -a 2048 "$DISK"
 
-    options=$(awk '/^[^#]/ { print $3 }' /usr/share/zoneinfo/zone.tab)
-    prompt="Select a timezone: "
-    TIMEZONE=$(fuzzySelection)
+    sgdisk -n 1::+1G -t=1:ef00 -c=1:"EFI" "$DISK"
+    sgdisk -n 2::-0 -t=2:8300 -c=2:"ROOT" "$DISK"
 
-    options=$(localectl list-keymaps)
-    prompt="Select a layout: "
-    KEYMAP=$(fuzzySelection)
-
-    printf "\n%b%s%b\n" "${GREEN}INFO:${RC} " "Fetching fastest mirrors for ${COUNTRY}..."
-    reflector --country "${COUNTRY}" --latest 5 --protocol https --save /etc/pacman.d/mirrorlist >/dev/null 2>&1
+    partprobe "$DISK"
 }
 
-initScript
-userInfo
-diskSelection
-regionSelection
-clear
+diskMount() {
+    case "$DISK" in
+        *nvme*)
+            P1="${DISK}p1"
+            P2="${DISK}p2"
+            ;;
+        *)
+            P1="${DISK}1"
+            P2="${DISK}2"
+            ;;
+    esac
 
-# --------------------------------------
-# --- Erase Disk / Create Partitions ---
-# --------------------------------------
+    mkfs.fat -F 32 -n "EFI" "$P1"
+    mkfs.ext4 -F -L "ROOT" "$P2"
 
-umount -A -R /mnt || true
-sgdisk -Z "${DISK}"
-sgdisk -a 2048 "${DISK}"
+    mount "$P2" /mnt
+    mount --mkdir "$P1" /mnt/boot
+}
 
-sgdisk -n 1::+1G -t=1:ef00 -c=1:"EFI" "${DISK}"
-sgdisk -n 2::-0 -t=2:8300 -c=2:"ROOT" "${DISK}"
+getMirrors() {
+    printf "%b%s%b\n" "INFO: Fetching fastest mirrors for $MIRROR..."
+    reflector --country $MIRROR --latest 5 --protocol https --save /etc/pacman.d/mirrorlist
+}
 
-partprobe "${DISK}"
+baseSystem() {
+    if [ "$(systemd-detect-virt)" = "none" ]; then
+        pacstrap -K /mnt base linux-lts linux-firmware
+    else
+        pacstrap -K /mnt base linux-lts
+    fi
+}
 
-# -----------------------------------------
-# --- Format Partitions / Mount to /mnt ---
-# -----------------------------------------
+setSystem() {
+    genfstab -U /mnt >> /mnt/etc/fstab
+    arch-chroot /mnt /bin/bash <<EOF
 
-case "${DISK}" in
-    *nvme*)
-        P1="${DISK}p1"
-        P2="${DISK}p2"
-        ;;
-    *)
-        P1="${DISK}1"
-        P2="${DISK}2"
-        ;;
-esac
+    printf "%b\n" "INFO: Setting timezone..."
+    ln -sf /usr/share/zoneinfo/$TIMEZONE /etc/localtime
+    hwclock --systohc
 
-mkfs.fat -F 32 -n "EFI" "${P1}"
-mkfs.ext4 -F -L "ROOT" "${P2}"
+    printf "%b\n" "INFO: Setting locale..."
+    sed -i 's/^#pt_BR.UTF-8 UTF-8/pt_BR.UTF-8 UTF-8/' /etc/locale.gen
+    locale-gen
+    printf "%b\n" "LANG=pt_BR.UTF-8" > /etc/locale.conf
 
-mount "${P2}" /mnt
-mount --mkdir "${P1}" /mnt/boot
+    printf "%b\n" "INFO: Setting keymap..."
+    printf "%b%s\n" "KEYMAP=" "$KEYMAP" > /etc/vconsole.conf
 
-# ----------------------------------------------------------------------
-# --- Install Base System / Generate Fstab / Chroot Installed System ---
-# ----------------------------------------------------------------------
+    printf "%b\n" "INFO: Setting hostname..."
+    printf "%s\n" "$HOSTNAME" > /etc/hostname
 
-if [ -n "${UCODE}" ] && [ "${VM}" = "n" ]; then
-    pacstrap -K /mnt base base-devel git linux-lts linux-firmware "${UCODE}" networkmanager 
-elif [ -n "${UCODE}" ] && [ "${VM}" = "y" ]; then
-    pacstrap -K /mnt base base-devel git linux-lts "${UCODE}" networkmanager 
-elif [ ! -n "${UCODE}" ] && [ "${VM}" = "n" ]; then
-    pacstrap -K /mnt base base-devel git linux-lts linux-firmware networkmanager 
-else
-    pacstrap -K /mnt base base-devel git linux-lts networkmanager
-fi
+    printf "%b\n" "INFO: Setting network manager..."
+    pacman -S --noconfirm --needed networkmanager
+    systemctl enable NetworkManager
 
-genfstab -U /mnt >> /mnt/etc/fstab
-arch-chroot /mnt /bin/bash <<EOF
+    printf "%b\n" "INFO: Setting microcode..."
+    if grep -q "GenuineIntel" /proc/cpuinfo; then
+        pacman -S --noconfirm --needed intel-ucode
+    elif grep -q "AuthenticAMD" /proc/cpuinfo; then
+        pacman -S --noconfirm --needed amd-ucode
+    else
+        printf "%b\n" "WARNING: Unable to detect CPU vendor. Skipping microcode installation..."
+    fi
 
-# --------------------------------------------
-# --- Enable Multilib / Color / ILoveCandy ---
-# --------------------------------------------
+    printf "%b\n" "INFO: Setting user..."
+    pacman -S --noconfirm --needed sudo
+    useradd -m -G wheel -s /bin/bash $USER
+    printf "%s:%s\n" "$USER" "$PASSWORD" | chpasswd
+    sed -i 's/^# %wheel ALL=(ALL:ALL) NOPASSWD: ALL/%wheel ALL=(ALL:ALL) NOPASSWD: ALL/' /etc/sudoers
 
-sed -i 's/^#Color/Color\nILoveCandy/' /etc/pacman.conf
-sed -i "/\[multilib\]/,/Include/"'s/^#//' /etc/pacman.conf
-pacman -Sy --noconfirm --needed
+    printf "%b\n" "INFO: Setting grub..."
+    pacman -S --noconfirm --needed grub efibootmgr
+    grub-install --target=x86_64-efi --efi-directory=/boot --bootloader-id=GRUB --removable
+    grub-mkconfig -o /boot/grub/grub.cfg
 
-# --------------------------------------
-# --- Set Locale / Timezone / Keymap ---
-# --------------------------------------
-
-sed -i "s/^#${LOCALE_LONG}/${LOCALE_LONG}/" /etc/locale.gen
-locale-gen
-printf "LANG=%s\n" "${LOCALE}" > /etc/locale.conf
-
-ln -sf /usr/share/zoneinfo/${TIMEZONE} /etc/localtime
-hwclock --systohc
-
-printf "KEYMAP=%s\n" "${KEYMAP}" > /etc/vconsole.conf
-
-if [ "${KEYMAP}" = "br-abnt2" ]; then
-    mkdir -p /etc/X11/xorg.conf.d
-    printf 'Section "InputClass"\n\tIdentifier "system-keyboard"\n\tMatchIsKeyboard "on"\n\tOption "XkbLayout" "br"\n\tOption "XkbModel" "abnt2"\nEndSection\n' > /etc/X11/xorg.conf.d/00-keyboard.conf
-fi
-
-# ---------------------------------------------
-# --- Create User / Set Sudo / Set Hostname ---
-# ---------------------------------------------
-
-useradd -m -G wheel -s /bin/bash "${USER}"
-printf "%s:%s\n" "${USER}" "${PASSWD}" | chpasswd
-printf "%s\n" "${HOST}" > /etc/hostname
-sed -i 's/^# *%wheel ALL=(ALL:ALL) NOPASSWD: ALL/%wheel ALL=(ALL:ALL) NOPASSWD: ALL/' /etc/sudoers
-
-# --------------------------------
-# --- Install Yay / AUR Helper ---
-# --------------------------------
-
-su - "${USER}" -c "cd /tmp && rm -rf yay-bin && git clone https://aur.archlinux.org/yay-bin.git && cd yay-bin && makepkg --noconfirm -si"
-
-# -----------------------------
-# --- Enable NetworkManager ---
-# -----------------------------
-
-systemctl enable NetworkManager.service
-
-# -------------------------------------
-# --- Set Systemd-Boot / Bootloader ---
-# -------------------------------------
-
-bootctl install
-printf "default @saved\ntimeout 0\nconsole-mode max\neditor no\n" > /boot/loader/loader.conf
-
-if [ -n "${UCODE}" ]; then
-    printf "title Arch Linux (LTS)\nlinux /vmlinuz-linux-lts\ninitrd /%s.img\ninitrd /initramfs-linux-lts.img\noptions root=UUID=%s rw\n" "${UCODE}" "${ROOT_UUID}" > /boot/loader/entries/lts.conf
-else
-    printf "title Arch Linux (LTS)\nlinux /vmlinuz-linux-lts\ninitrd /initramfs-linux-lts.img\noptions root=UUID=%s rw\n" "${ROOT_UUID}" > /boot/loader/entries/lts.conf
-fi
 EOF
+}
 
-# -------------------------------------------
-# --- Finish Installation / Reboot System ---
-# -------------------------------------------
+checkEnv
+clear
+setfont ter-v18b
+userInformation
+diskSelection
+diskFormat
+diskMount
+getMirrors
+baseSystem
+setSystem
 
-printf "%b\n" "${GREEN}Rebooting system in 5 seconds...${RC}"
+printf "%b\n" "INFO: Rebooting system in 5 seconds..."
 sleep 1
-printf "%b\n" "${GREEN}Rebooting system in 4 seconds...${RC}"
+printf "%b\n" "INFO: Rebooting system in 4 seconds..."
 sleep 1
-printf "%b\n" "${GREEN}Rebooting system in 3 seconds...${RC}"
+printf "%b\n" "INFO: Rebooting system in 3 seconds..."
 sleep 1
-printf "%b\n" "${GREEN}Rebooting system in 2 seconds...${RC}"
+printf "%b\n" "INFO: Rebooting system in 2 seconds..."
 sleep 1
-printf "%b\n" "${GREEN}Rebooting system in 1 second...${RC}"
+printf "%b\n" "INFO: Rebooting system in 1 second..."
 sleep 1
 systemctl reboot
